### ISSUE TITLE
"fatally missing registry entires" 

### ISSUE THREAD

**Issue by S0ORiYa** [xJon/Tekkit-SMP#15]
### Was this help requested before?

- [X] No, it was not.

### Please provide a link to your crash report or latest.log, if relevant

https://mclo.gs/KBP7gSI

### If you have any, please provide a list of additional mods

tekkit smp v1.01

### Please describe what you need help with

ive got a tekkit smp server 1.01. windows os has no problem joining. macos has issues joining i copied the config folder and pasted it on the macos from windows. it still says "fatally missing registry entires" 

this is the client log
[16:09:25] [User Authenticator #11/INFO] [minecraft/NetHandlerLoginServer]: UUID of player Lavacoco23 is 329243bb-e8b7-47e4-a47d-ecd71441eed0 [16:09:25] [Netty Server IO #16/INFO] [FML]: Client protocol version 2 [16:09:25] [Netty Server IO #16/INFO] [FML]: Client attempting to join with 219 mods : lostmagic@1.0,railway_depot_worker@1.4.0,linking_tweaks@1.0.0.0,thaumtweaks@0.3.5.3,gbook@2.9.5,tcresearchpatcher@1.12.2-1.1.3,buildcraftenergy@8.0.6-ec83d13d9ce2,universaltweaks@1.12.1,cta@@VERSION@,projecte@1.12.2-PE1.4.7,thaumicjei@1.6.0,hammercore@2.0.6.32,jeibees@0.9.0.5,ctm@MC1.12.2-1.0.2.31,reauth@4.0.7,justenoughdrags@1.4-beta.1,forgelin@1.8.4,microblockcbe@2.6.3.1,randompatches@1.12.2-1.22.1.10,morpheus@1.12.2-3.5.106,mystcraft_info@1.0.3.0,waila@1.8.26,snowrealmagic@0.7.1,galacticraftplanets@4.0.7,guideapi@1.12-2.1.8-63,jeresources@0.9.2.60,mcmultipart@2.5.3,mainmenuscale@1.0,mysticallib@1.12.2-1.13.0,packcrashinfo@%VERSION%,matmos@1.12.2-36.0.1,betterpingdisplay@1.0,industrialforegoing@1.12.2-1.12.2,tipthescales@1.0.4,unidict@1.12.2-3.0.10,mia@1.12.2-0.2.2a,craftingtableiv@1.12.2-1.5.123,buildcraftsilicon@8.0.6-ec83d13d9ce2,moresoundconfig@1.0.4,modtweaker@4.0.19,fairylights@2.1.10,resourceloader@1.5.3,eleccore@1.9.453,projectred-core@4.9.4.120,mocreatures@12.4.5,ic2@2.8.1001,buildcraftbuilders@8.0.6-ec83d13d9ce2,aquaacrobatics@1.15.4,jepb@1.2.1,lunatriuscore@1.2.0.42,buildcraftfactory@8.0.6-ec83d13d9ce2,jexclusives@1.1.3,teslacorelib@1.0.18,projectred-fabrication@4.9.4.120,thaumcraftfix@1.12.2-1.0.3,projectred-exploration@4.9.4.120,projectred-transportation@4.9.4.120,FML@8.0.99.99,projectred-integration@4.9.4.120,rcw@2.0,buildcraftcompat@8.0.6-ec83d13d9ce2,advancedsolars@1.0.11,crimsonrevelations@1.1.0,forgemultipartcbe@2.6.3.1,ic2-classic-spmod@0.0.0.0,particleculling@v1.4.3,codechickenlib@3.2.3.358,wailaharvestability@1.1.12,binniedesign@2.5.1.212,cctweaked@1.89.2,configanytime@3.0,clienttweaks@3.1.11,ctgui@1.0.0,renderlib@1.3.5,smoothfont@mc1.12.2-2.1.4,jei@4.25.5,custommainmenu@2.0.9.1,fluxcables@1.0.0,loliasm@5.20,lemonlib@1.3.0,smoothfontcore@mc1.12.2-2.1.4,thaumicperiphery@0.3.1,naturescompass@1.8.5,asmodeuscore@1.0.2,plethora-core@1.2.3,ic2cuumatter@1.1.3,eleccoreloader@1.9.453,inventorytweaks@1.63+release.109.220f184,mystcraft@0.13.7.06,extrabees@2.5.1.212,micdoodlecore@4.0.7,isorropia@0.1.13,crafttweaker@4.1.20,forge@14.23.5.2860,testdummy@1.12,phosphor-lighting@1.12.2-0.2.9.3,forbiddenmagicre@0.7.5,ironchest@1.12.2-7.0.67.844,minecraft@1.12.2,vmfixes@1.12.2-1.0.7,mousetweaks@3.1.4,bspkrscore@7.6.0.1,jeiintegration@1.6.0,debark@0.1.3,loottweaker@0.4.1,autoreglib@1.3-32,smooth-scrolling-everywhere@1.1,galacticraftcore@4.0.7,entityculling@6.4.3,mrtjpcore@2.1.5.1,railcraft@12.1.0-beta-8.2.1,viewemc@v8,moresoundconfigcore@1.0.0,appleskin@1.0.14,minecraftmultipartcbe@2.6.3.1,recipehandler@0.13,damagetilt@0.1.0,netherendingores@1.12.2-1.4.2,gravisuit@1.0.8.10,railcraft_tweaker@0.1.0,advanced_smelter@1.1.0,forestry@5.8.2.422,defaultoptions@9.2.8,buildcraftlib@8.0.6-ec83d13d9ce2,tc_integration@1.1-1.12.2,welectromagic@0.0.15,binniecore@2.5.1.212,modernsplash@@VERSION@,additionalbanners@1.1.77,kleeslabs@5.4.12,reborncore@3.19.5,controlling@3.0.10,spaceambient@0.0.1,projectred-illumination@4.9.4.120,cofhworld@1.4.0,thaumicwaila@1.12.2-0.0.2,plethora@1.2.3,thaumcraft@6.1.BETA26,weaponmod@1.22.1,thaumictinkerer@1.12.2-5.5.1-Unofficial,experiencebugfix@1.0.0.0,extratrees@2.5.1.212,thaumicwonders@1.9.0,charset@0.5.6.6,crafttweakerjei@2.0.3,moremystcraft@1.0.0,modularforcefieldsystem@4.0.1.5,mtlib@3.0.7,botany@2.5.1.212,tekkit2jc@1.0.0,sc_ic2c_compat@1.0.0,dogslie@1.0.2,cableflux@12.2.4,helpfixer@1.12.1-1.5.18,teslacorelib_registries@1.0.18,additionalpipes@6.0.0.9,cathedral@1.12.2-1.9.9,lpb@1.0,balkonsexpansion@1.0.0,projectred-transmission@4.9.4.120,gunpowderlib@1.12.2-1.1,asmc@1.0.2,justenoughmagiculture@1.12.2-1.1.5,computercraft@1.89.2,moreoverlays@1.15.1-technic1,irontanks@1.12.2-2.1.0-beta.18,jetif@1.5.2,zettaindustries@1.3,thaumicaugmentation@1.12.2-2.1.13,energycontrol@1.12.2-0.3.2a,badwithernocookiereloaded@1.12.2-3.4.18,buildcraftcore@8.0.6-ec83d13d9ce2,mixinbooter@9.3,asielib@1.0.0,reachfix@1.0.10,buildcrafttransport@8.0.6-ec83d13d9ce2,crimsonwarfare@1.5,pages@2.0.0.1,pip@7.0.0,mcp@9.42,treecapitator@1.43.0,comforts@1.4.1.3,tumbleweed@1.12-0.4.7,ifpatcher@2.4.0,computronics@1.6.7,ichunutil@7.2.2,weisscoreterminal@0.1.1,enderstorage@2.4.6.137,projectred-compat@1.0,sledgehammer@1.12.2-2.0.26,akashictome@1.2-12,magicbees@1.0,buildcraftrobotics@8.0.6-ec83d13d9ce2,backups@1.5.7,playerplates@1.12.2-1.3.1.1,ltta@1.4.0,baubles@1.5.2,exchangers@1.12.2-2.10.3,mystlibrary@1.12.2-0.0.3.2,modernbetaforge@1.0.2.1,weisscore@0.1.1,vintagefix@0.5.1,projectred-relocation@4.9.4.120,stevescarts@2.4.32.137,genetics@2.5.1.212,integrationforegoing@1.12.2-1.11,quark@r1.6-185,fluidlogged_api@2.2.7,blockcraftery@1.12.2-1.3.1,projectred-expansion@4.9.4.120,statues@1.0.1,schematica@1.8.0.169,wrcbe@2.3.2,wanionlib@1.12.2-2.91,chisel@MC1.12.2-1.0.2.45,voxelmap@1.9.25,logisticspipes@0.10.4.49,chiselsandbits@14.33,translocators@2.5.2.81 [16:09:25] [Netty Server IO #16/INFO] [FML]: Attempting connection with missing mods [colorchat, k4lib] at CLIENT [16:09:25] [Netty Server IO #16/INFO] [CodeChickenLib-ConfigSync]: Skipping config sync, No mods have registered a syncable config. [16:09:26] [Netty Server IO #16/ERROR] [FML]: NetworkDispatcher exception java.io.IOException: An existing connection was forcibly closed by the remote host at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_421] at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_421] at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_421] at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_421] at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_421] at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[PooledUnsafeDirectByteBuf.class:?] at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[AbstractByteBuf.class:?] at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[NioSocketChannel.class:?] at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [AbstractNioByteChannel$NioByteUnsafe.class:?] at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [NioEventLoop.class:?] at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [NioEventLoop.class:?] at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [NioEventLoop.class:?] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [NioEventLoop.class:?] at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:?] at java.lang.Thread.run(Unknown Source) [?:1.8.0_421] [16:09:26] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: Lavacoco23 lost connection: Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host [16:09:26] [Server thread/INFO] [minecraft/DedicatedServer]: Lavacoco23 left the game

**Comment by S0ORiYa** [comment]
https://mclo.gs/mXrHaXM

**Comment by S0ORiYa** [comment]
https://mclo.gs/MbPSWYC

**Comment by xJon** [comment]
Can you try troubleshooting something?
- (Make a backup of your server world)
- Remove the BuildCraft mod
- Try to connect again with the client. Does it now work?

**Comment by S0ORiYa** [comment]
Alright I’ll try it tonight, as for SMP v1.0.0 the macOS couldn’t connect and the windows(host) could connect.

**Comment by xJon** [comment]
Also, can you share your macOS version, and whether it's using an M or Intel processor?

**Comment by S0ORiYa** [comment]
https://mclo.gs/KE8Fh4C this is my client logs(windows). i've also noticed most of my buildcraft items are missing from the server.
As for macos version its Ventura. and yes i am using technic launcher for all of the clients

**Comment by xJon** [comment]
Did you try what I've suggested as "Option 2"?

**Comment by xJon** [comment]
Another option, can you try to edit your server's `\config\mystcraft\symbols.cfg` file to have these contents?
https://api.mclo.gs/1/raw/YHUyBbF

**Comment by xJon** [comment]
I've now applied those changes by default in version `1.0.2` - does the issue still happen with it?

**Comment by S0ORiYa** [comment]
I played on tekkit 2 instead. Since it was more stable, I’ll let you know by end of the week. Thanks for the help

**Comment by xJon** [comment]
Indeed this issue was to do with Mystcraft, which is not present in Tekkit 2.

**Comment by xJon** [comment]
@peto1290 Can you do what I previously suggested and report back?
> - Option 2 
>   - (Make a backup of your server world)
>   - Remove the BuildCraft mod
>   - Try to connect again with the client. Does it now work?

**Comment by peto1290** [comment]
Okey, I removed BuildCraft Mod from server folder MODS and server dont wont to RUN here is massage from console: https://mclo.gs/DeeBeKe 

And here is full massage from console when server normally working, only me cant join. Here you can see my cousin as Peyteysn can normally join with no error but me petrikk cant join and error: https://mclo.gs/1oaMbEt

**Comment by xJon** [comment]
@peto1290 Oversight on my end, to test this you'd also need to remove the BuildCraft mod addons: Additional Pipes, Iron Tank

**Comment by peto1290** [comment]
YESSS!!!! Im on server FINALLY! It works, I Removed BuildCraft and Additional Pipes and Iron Tank And now i Can normally connect.

**Comment by xJon** [comment]
Okay! That is progress. So we know the issue is caused by Mystcraft + BuildCraft Remastered. I will continue testing and let you know if I have a suggested fix.

In the meantime, it would be quite unfortunate to play without BuildCraft! I would suggest you to consider either re-adding BuildCraft and its addons and removing Mystcraft instead, or hosting the server on Windows/Linux.

Nevertheless, hopefully this issue can get resolved soon, will keep you posted.

**Comment by xJon** [comment]
@peto1290 Can you run an additional test? With all the mods included, try to delete the custom `config\mystcraft\symbols.cfg` file that is shipped with the modpack, both on the server-side and client-side, then see if you get any error.
It'd be also helpful if you can share the newly generated `symbols.cfg` from both the server and client (on your Mac), and see if they match or not.

I tried testing this many times in the past but because I don't have a Mac, it is not exactly possible, so your help troubleshooting is appreciated.

**Comment by peto1290** [comment]
Yes, of course I'm going to try it right away. Even though I'm not at home, I'm remotely connecting to my PC and going to try it.

I am very happy to help you with anything. I have macOS latest version Sequoia 15.3.2. MacBook PRO 2020 with M1 Apple silicon 8 gb RAM

I can be your "BETA TESTER" 😁

okay, I'm going to try it and let you know right away, I'll try to upload those files too.

**Comment by peto1290** [comment]
Here is Symbols.cfg FROM WINDOWS HOST PC - WHERE SERVER RUNS : https://mclo.gs/SaxVJyB 
And here is Symbols.cfg from my Macbook : https://mclo.gs/o0yaNl2

In bottom line you have label what is from what.

**Comment by peto1290** [comment]
I tried one more time, here is from SERVER PC : https://mclo.gs/DhNmpwU
And this is from MAC: https://mclo.gs/Yv382gF

And i Forgot to say, i Cant connect to server, same massage Fatally missing registry entries, so this dont work.

**Comment by xJon** [comment]
@peto1290 That is absolutely bizarre, notice how this BuildCraft section of the file does not generate on macOS like it does on Windows:
![Image](https://github.com/user-attachments/assets/08c0dcc0-f2ef-4892-8355-145007eff83d)

Can you please also compare the client-side on macOS, where the modpack client is installed?

**Comment by peto1290** [comment]
Sorry, can you please explain more precisely what I should do? Because I don't understand.

Do I need to copy this symbols.cfg file from Windows PC to MacBook and tested ?

**Comment by xJon** [comment]
@peto1290 No, when I said "client" I was referring to the modpack client running from the Technic Launcher, in contrast to the dedicated server. You could access its installation directory through the launcher:
![Image](https://github.com/user-attachments/assets/25ce5c11-2b79-49e9-ba9d-0a6e6a2b931a)

If you can compare the newly generated `\modpacks\tekkit-smp\config\mystcraft\symbols.cfg` file there between macOS and Windows.

**Comment by peto1290** [comment]
can we connect somewhere on some communication service for easier communication?

I reinstalled technic launcher and reinstalled Tekkit SMP and here is the file from modpack->tekkit-smp->config->mystcraft->symbols.cfg from clean installation before the first power-on tekkit smp : https://mclo.gs/mpzlaJM
Now I have here this missing lines, but unfortunettly my Windows PC where server runs turn off and now i cant try if it work, i will be home today at +- 15:00 hour. 

on a windows pc where tekkit smp runs fine i will be physically there sometime around 3:00 pm today (15:00 hour)

and thank you for trying to help me, I'm very happy and thank you for that.

When i will arive home i will write you. Have a good night.

**Comment by xJon** [comment]
@peto1290 Can you try to delete that file and see how it re-generates on the client on macOS?

If you want you can join Technic's Discord (https://discord.com/invite/technic) and find me there.

Edit: Another potential fix, try to replace the BuildCraft version to this one: https://www.curseforge.com/minecraft/mc-mods/bc-remastered/files/5672415, and see if the necessary lines are generated on the server:
```
    buildcraftenergy {
        B:modmat_fluid_block_fuel_0.enabled=true
        B:modmat_fluid_block_oil_0.enabled=true
    }
```

**Comment by peto1290** [comment]
Okey i can quickly tested. Now i deleted this symbols file and im starting tekkit smp. 

Here is new file what tekkit smp created now. https://mclo.gs/0ais5UT 

Interesting, after clear installation this lines was here and now when i deleted symbols file tekkit smp created new but this lines missing.  

Okey i will try it in afternoon i will find you on discord and i will write you. Thanks for everything have a good night

**Comment by xJon** [comment]
@peto1290 Interesting, so the lines did not generate also on the client (where the modpack is installed), right? This test was not done on the server?

**Comment by xJon** [comment]
Another suggestion: add `-Dbuildcraft.lib.migrate.debug=true` to the server launch script, and then share the entire server log.

**Comment by xJon** [comment]
Thanks to @peto1290's extensive testing, we now better understand the issue (with the updated title).

The current workaround is to make sure Mystcraft's BuildCraft liquid integration is disabled on the server, so it is compatible with macOS clients:
```
    buildcraftenergy {
        B:modmat_fluid_block_fuel_0.enabled=false
        B:modmat_fluid_block_oil_0.enabled=false
    }
```
In `config\mystcraft\symbols.cfg`.

Going forward I might apply this workaround permanently to everyone although it means non-macOS systems will miss out on this small Mystcraft-BuildCraft integration.

**Comment by xJon** [comment]
Starting `1.0.3`, all servers have BuildCraft's oil and fuel Mystcraft integration as disabled by default, as a workaround for Mac compatibility due to this bizarre issue.

Server owners who don't have any Mac clients connecting to them can manually re-enable this for the feature.
